<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.salesforce.multicloudj</groupId>
        <artifactId>multicloudj-parent</artifactId>
        <version>0.5.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>multicloudj-examples</artifactId>
    <packaging>jar</packaging>
    <name>MultiCloudJ - Examples</name>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.34</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.google.inject</groupId>
            <artifactId>guice</artifactId>
        </dependency>
        <dependency>
            <groupId>com.salesforce.multicloudj</groupId>
            <artifactId>sts-client</artifactId>
        </dependency>
        <dependency>
            <groupId>com.salesforce.multicloudj</groupId>
            <artifactId>blob-client</artifactId>
        </dependency>
        <dependency>
            <groupId>com.salesforce.multicloudj</groupId>
            <artifactId>docstore-client</artifactId>
        </dependency>
        <dependency>
            <groupId>com.salesforce.multicloudj</groupId>
            <artifactId>pubsub-client</artifactId>
        </dependency>
        <dependency>
            <groupId>com.salesforce.multicloudj</groupId>
            <artifactId>dbbackuprestore-client</artifactId>
        </dependency>
        <dependency>
            <groupId>com.salesforce.multicloudj</groupId>
            <artifactId>iam-client</artifactId>
        </dependency>
        <dependency>
            <groupId>com.salesforce.multicloudj</groupId>
            <artifactId>docstore-gcp-firestore</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.salesforce.multicloudj</groupId>
            <artifactId>pubsub-gcp</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.salesforce.multicloudj</groupId>
            <artifactId>pubsub-aws</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.salesforce.multicloudj</groupId>
            <artifactId>sts-gcp</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.salesforce.multicloudj</groupId>
            <artifactId>blob-aws</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.salesforce.multicloudj</groupId>
            <artifactId>blob-gcp</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.salesforce.multicloudj</groupId>
            <artifactId>sts-aws</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.salesforce.multicloudj</groupId>
            <artifactId>docstore-aws</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.salesforce.multicloudj</groupId>
            <artifactId>iam-aws</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.salesforce.multicloudj</groupId>
            <artifactId>iam-gcp</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.salesforce.multicloudj</groupId>
            <artifactId>dbbackuprestore-aws</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.salesforce.multicloudj</groupId>
            <artifactId>dbbackuprestore-gcp-firestore</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.salesforce.multicloudj</groupId>
            <artifactId>dbbackuprestore-ali</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.salesforce.multicloudj</groupId>
            <artifactId>registry-client</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.salesforce.multicloudj</groupId>
            <artifactId>registry-gcp</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.salesforce.multicloudj</groupId>
            <artifactId>registry-aws</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.12.0</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>2.0.15</version>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.18.0</version>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

    </dependencies>

    <properties>
        <checkstyle.skip>true</checkstyle.skip>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.3.0</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <classpathPrefix>lib/</classpathPrefix>
                            <mainClass>com.salesforce.multicloudj.docstore.Main</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.4.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>com.salesforce.multicloudj.docstore.Main</mainClass>
                                </transformer>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>delombok</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <sourceDirectory>src/main/java</sourceDirectory>
                    <outputDirectory>${project.build.directory}/generated-sources/delombok</outputDirectory>
                    <addOutputDirectory>false</addOutputDirectory>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>