<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.salesforce.multicloudj</groupId>
        <artifactId>multicloudj-parent</artifactId>
        <version>0.5.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>dbbackuprestore</artifactId>
    <packaging>pom</packaging>
    <name>MultiCloudJ DB Backup Restore</name>
    <description>MultiCloudJ Database Backup and Restore Service</description>
    <modules>
        <module>dbbackuprestore-aws</module>
        <module>dbbackuprestore-ali</module>
        <module>dbbackuprestore-client</module>
        <module>dbbackuprestore-gcp-firestore</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>com.google.inject</groupId>
            <artifactId>guice</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.auto.service</groupId>
            <artifactId>auto-service</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>

</project>
